// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATcKi6noJkCVUOE6np6r0fAkJsoPUqTYY',
    appId: '1:1039976862062:web:5bf4e1d1f2f6653d3a717f',
    messagingSenderId: '1039976862062',
    projectId: 'news-app-11fe2',
    authDomain: 'news-app-11fe2.firebaseapp.com',
    storageBucket: 'news-app-11fe2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClg0zVFQdA3lXVYLVQ715ZeWWLSNSHOvE',
    appId: '1:1039976862062:android:6d053ca91a706ae63a717f',
    messagingSenderId: '1039976862062',
    projectId: 'news-app-11fe2',
    storageBucket: 'news-app-11fe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBnMZH9ce3hkFlWq7OTOhDVdV9rGJ3DPw',
    appId: '1:1039976862062:ios:65b7d05cceee843f3a717f',
    messagingSenderId: '1039976862062',
    projectId: 'news-app-11fe2',
    storageBucket: 'news-app-11fe2.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );
}
